// @ts-nocheck -- Ajv's ESM runtime export and its .d.ts default export disagree under Node's TS stripping.
/** Generate a dependency-free Ajv standalone reader for v2 public artifacts. */
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { Ajv2020 } from 'ajv/dist/2020.js';
import { default as standaloneCode } from 'ajv/dist/standalone/index.js';

const root = resolve(import.meta.dirname, '..');
const schemaNames = ['common-v2.schema.json', 'campaign-v2.schema.json', 'artifacts-v2.schema.json', 'finding-v2.schema.json', 'corpus-v2.schema.json', 'experiment-v2.schema.json', 'checkpoint-v2.schema.json', 'report-v2.schema.json'];
const reportId = 'https://jevfuzz.dev/schema/report-v2.schema.json';
const findingId = 'https://jevfuzz.dev/schema/finding-v2.schema.json';
const ajv = new Ajv2020({ strict: true, allowUnionTypes: true, code: { source: true, esm: true } });
// Standalone code can serialize regular expressions, while arbitrary format callbacks
// would require an Ajv runtime import. Semantic timestamp parsing remains in artifact IO.
ajv.addFormat('date-time', /^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d+)?(?:Z|[+-]\d\d:\d\d)$/);
for (const name of schemaNames) ajv.addSchema(JSON.parse(await readFile(resolve(root, 'schemas', name), 'utf8')));
if (!ajv.getSchema(reportId) || !ajv.getSchema(findingId)) throw new Error('report schemas did not compile');
const standalone = standaloneCode(ajv, { validateReport: reportId, validateFinding: findingId });
const helperImport = /const (func\d+) = require\("ajv\/dist\/runtime\/ucs2length"\)\.default;/;
const helperMatch = standalone.match(helperImport);
if (!helperMatch || (standalone.match(/require\("ajv\/dist\/runtime\//g) ?? []).length !== 1 || /^import\s/m.test(standalone)) throw new Error('unexpected Ajv standalone runtime helpers');
// Verbatim implementation from ajv@8.17.1 dist/runtime/ucs2length.js (MIT), whose
// source cites punycode.js's MIT-licensed ucs2.decode implementation.
const helper = `function ucs2length(str) {
    const len = str.length;
    let length = 0;
    let pos = 0;
    let value;
    while (pos < len) {
        length++;
        value = str.charCodeAt(pos++);
        if (value >= 0xd800 && value <= 0xdbff && pos < len) {
            value = str.charCodeAt(pos);
            if ((value & 0xfc00) === 0xdc00)
                pos++;
        }
    }
    return length;
}`;
const selfContained = standalone.replace(helperImport, `const ${helperMatch[1]} = ucs2length;`);
const output = `// Generated by scripts/generate-report-validator.ts using Ajv 8 standaloneCode. Do not edit.\n// @ts-nocheck\nimport { FuzzError } from './util.ts';\n// Inlined Ajv 8.17.1 ucs2length helper; see generator for MIT provenance.\n${helper}\n${selfContained}\nexport function validateReportArtifact(raw){if(!validateReport(raw))throw new FuzzError('CONFIG','invalid v2 report artifact')}\nexport function validateFindingShape(raw){if(!validateFinding(raw))throw new FuzzError('CONFIG','invalid v2 finding artifact')}\n`;
await writeFile(resolve(root, 'src/report-validator.ts'), output);
