import { declaredContentPath } from './config.ts';
import { globSync } from 'node:fs';
import { basename, dirname, relative, resolve } from 'node:path';
import { parseConfig, validateRequest } from './config.ts';
import { atPath, pathTokens } from './util.ts';
import type { CampaignConfig, CampaignSeed, Contract, Policy, PolicyExpression } from './campaign-types.ts';
import { assert, integer, record } from './util.ts';
import { boundedJson, readJson } from './storage.ts';
import { validateBudget } from './engine/budget.ts';
import { wireHash } from './identity.ts';

const ops = new Set(['question_id_rename','question_order','choice_criteria_order','object_key_order','unordered_array_shuffle','irrelevant_field_injection','text_normalization','choice_label_rename','proposal']);
const fields=(v:Record<string,unknown>,a:string[],w:string)=>assert(Object.keys(v).every(k=>a.includes(k)),`unsupported field in ${w}`);
const text=(v:unknown,w:string)=>{assert(typeof v==='string'&&v.length>0&&v.length<=512,`${w} must be non-empty text`);return v;};
const strings=(v:unknown,w:string)=>{assert(Array.isArray(v)&&v.every(x=>typeof x==='string'),`${w} must be strings`);return v as string[];};
const unit=(v:unknown,w:string,positive=false)=>{assert(typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=1&&(!positive||v>0),`${w} invalid`);return v;};

function parseSeed(raw:unknown,fallback:string):CampaignSeed[]{
  assert(record(raw),'parseCampaign accepts inline seed objects');fields(raw,['id','request','mutations','source'],'seed');const source=raw.source===undefined?undefined:text(raw.source,'seed source');
  if(record(raw.request)&&raw.request.version===1)return parseConfig(raw.request,fallback).cases.map(c=>({id:raw.id===undefined?c.id:text(raw.id,'seed id'),request:c.request,mutations:c.mutations,...(source?{source}:{})}));
  const request=validateRequest(raw.request);boundedJson(request,64,100_000);const c=parseConfig({version:1,name:'seed',model:request.model,cases:[{id:'seed',request,...(raw.mutations===undefined?{}:{mutations:raw.mutations})}]}).cases[0]!;
  return [{id:raw.id===undefined?fallback:text(raw.id,'seed id'),request,mutations:c.mutations,...(source?{source}:{})}];
}

export function parseContract(raw:unknown,seeds:readonly CampaignSeed[]):Contract{
  assert(record(raw),'contract must be object');fields(raw,['id','question','relation','projection','mutations','admissibility','assumptions','required','tolerance','minimumEffect','units','direction','labelMapping'],'contract');
  const id=text(raw.id,'contract id'),question=text(raw.question,'contract question'),qs=seeds.map(s=>s.request.questions[question]);assert(qs.every(Boolean),'contract question missing');
  const projection=raw.projection??qs[0]!.type;assert(['choice','noul','score','policy'].includes(String(projection)),'invalid contract projection');if(projection!=='policy')assert(qs.every(q=>q!.type===projection),'contract projection type mismatch');
  const relation=raw.relation??'invariant';assert(['invariant','equivariant','bounded_shift','directional'].includes(String(relation)),'invalid contract relation');
  const mutations=raw.mutations??['question_id_rename'];assert(Array.isArray(mutations)&&mutations.length>0&&mutations.every(x=>typeof x==='string'&&ops.has(x)),'invalid contract mutation');
  const admissibility=raw.admissibility??(mutations.every(x=>x==='question_id_rename')?'structural':'declared');assert(['structural','declared','hypothesis'].includes(String(admissibility)),'invalid admissibility');assert(admissibility!=='structural'||mutations.every(x=>x==='question_id_rename'),'structural contracts allow only question_id_rename');
  assert(!mutations.includes('proposal') || admissibility==='hypothesis','proposal mutations require hypothesis admissibility');
  const assumptions=raw.assumptions??[];assert(Array.isArray(assumptions)&&assumptions.every(x=>typeof x==='string'&&x.length>0),'invalid assumptions');if(admissibility==='declared')assert(assumptions.length>0,'declared contracts require assumptions');
  if(relation==='directional')assert(raw.direction==='increase'||raw.direction==='decrease','directional contract requires direction');else assert(raw.direction===undefined,'direction only applies to directional');
  for(const k of ['tolerance','minimumEffect'] as const)if(raw[k]!==undefined)assert(typeof raw[k]==='number'&&Number.isFinite(raw[k])&&raw[k]>=0,`invalid ${k}`);
  if(relation==='bounded_shift'||relation==='directional')assert(projection==='noul'||projection==='score','numeric relations require noul or score');
  if((relation==='bounded_shift'||relation==='directional')&&projection==='score')assert(typeof raw.units==='string'&&raw.units.length>0,'Score delta requires units');
  const mapping=raw.labelMapping;if(mutations.includes('choice_label_rename')){assert(admissibility==='declared'&&relation==='equivariant'&&projection==='choice'&&record(mapping),'choice_label_rename requires declared equivariant Choice mapping');const labels=Object.keys((qs[0]! as {criteria:Record<string,unknown>}).criteria), entries=Object.entries(mapping);assert(entries.length===labels.length&&new Set(entries.map(([,v])=>v)).size===labels.length&&entries.every(([,v])=>typeof v==='string'&&labels.includes(v)),'labelMapping must be complete bijection');}else assert(mapping===undefined,'labelMapping requires choice_label_rename');
  assert(raw.required===undefined||typeof raw.required==='boolean','contract required invalid');
  return {id,question,relation:relation as Contract['relation'],projection:projection as Contract['projection'],mutations:mutations as Contract['mutations'],admissibility:admissibility as Contract['admissibility'],assumptions,required:(raw.required??true) as boolean,...(raw.tolerance===undefined?{}:{tolerance:raw.tolerance as number}),...(raw.minimumEffect===undefined?{}:{minimumEffect:raw.minimumEffect as number}),...(raw.units===undefined?{}:{units:text(raw.units,'units')}),...(raw.direction===undefined?{}:{direction:raw.direction as 'increase'|'decrease'}),...(mapping===undefined?{}:{labelMapping:mapping as Record<string,string>})};
}

function expression(raw:unknown,seeds:readonly CampaignSeed[],depth=0,nodes:{n:number}={n:0}):PolicyExpression{
  assert(++nodes.n<=1024&&depth<=16&&record(raw),'policy expression invalid');if(Object.hasOwn(raw,'all')||Object.hasOwn(raw,'any')){assert(Object.keys(raw).length===1,'policy group invalid');const a=raw.all??raw.any;assert(Array.isArray(a)&&a.length>0,'policy group invalid');return Object.hasOwn(raw,'all')?{all:a.map(x=>expression(x,seeds,depth+1,nodes))}:{any:a.map(x=>expression(x,seeds,depth+1,nodes))};}
  fields(raw,['question','field','label','op','value'],'policy predicate');const q=text(raw.question,'policy question'),qs=seeds.map(s=>s.request.questions[q]);assert(qs.every(Boolean),'policy question missing');const field=raw.field;assert(['choice','noul','score','confidence','probability'].includes(String(field))&&['eq','ne','lt','lte','gt','gte'].includes(String(raw.op)),'policy predicate invalid');
  if(field==='choice'){assert(qs.every(x=>x!.type==='choice')&&typeof raw.value==='string'&&(raw.op==='eq'||raw.op==='ne')&&qs.every(x=>Object.hasOwn((x as any).criteria,raw.value as string)),'choice policy invalid');}
  else {assert(typeof raw.value==='number'&&Number.isFinite(raw.value),'numeric policy value required');if(field==='noul'||field==='confidence'||field==='probability')assert(raw.value>=0&&raw.value<=1,'unit policy value required');assert(field==='noul'?qs.every(x=>x!.type==='noul'):field==='score'?qs.every(x=>x!.type==='score'):(qs.every(x=>x!.type==='choice'||x!.type==='score')),'policy field question type mismatch');}
  const label=raw.label;if(field==='probability')assert(typeof label==='string'&&qs.every(x=>x!.type==='choice'?Object.hasOwn(x!.criteria,label):x!.type==='score'&&Number.isInteger(Number(label))&&Number(label)>=0&&Number(label)<x!.criteria.length),'probability label invalid');else assert(label===undefined,'label only applies to probability');return raw as unknown as PolicyExpression;
}
export function parsePolicy(raw:unknown,seeds:readonly CampaignSeed[]):Policy|undefined{if(raw===undefined)return undefined;assert(record(raw),'policy must be object');fields(raw,['version','rules','fallback'],'policy');const action=(v:unknown)=>{assert(typeof v==='string'&&v.length>0&&v.length<=512&&/^([^$]|\$\{[A-Za-z_][A-Za-z0-9_-]*\})*$/.test(v),'policy action invalid');for(const q of v.matchAll(/\$\{([A-Za-z_][A-Za-z0-9_-]*)\}/g))assert(seeds.every(s=>s.request.questions[q[1]!]?.type==='choice'),'policy template must reference Choice');return v;};assert(raw.version===1&&Array.isArray(raw.rules)&&raw.rules.length<=64,'policy invalid');return {version:1,fallback:action(raw.fallback),rules:raw.rules.map(r=>{assert(record(r),'policy rule invalid');fields(r,['when','action'],'policy rule');return {when:expression(r.when,seeds),action:action(r.action)};})};}

export function parseCampaign(value:unknown,filename='campaign.json'):CampaignConfig{
  boundedJson(value);
  assert(record(value),'campaign must be object');fields(value,['version','name','seeds','provider','contracts','search','oracle','budget','storage','reducers','policy'],'campaign');assert(value.version===2&&Array.isArray(value.seeds)&&value.seeds.length>0&&value.seeds.length<=10_000,'campaign seeds invalid');
  const all=value.seeds.flatMap((s,i)=>parseSeed(s,`${basename(filename)}-${i}`));assert(all.length<=10_000,'too many seeds');const seen=new Set<string>(),seeds=all.filter(s=>{const k=`${wireHash(JSON.stringify(s.request))}:${JSON.stringify(s.mutations)}`;if(seen.has(k))return false;seen.add(k);return true;}),duplicateSeeds=all.length-seeds.length;assert(new Set(seeds.map(s=>s.id)).size===seeds.length,'duplicate seed id');
  assert(['typesafe','cloudflare','custom'].includes(String(value.provider))&&Array.isArray(value.contracts)&&value.contracts.length>0,'campaign invalid');const contracts=value.contracts.map(c=>parseContract(c,seeds));assert(new Set(contracts.map(c=>c.id)).size===contracts.length,'duplicate contract id');
  assert(value.search===undefined||record(value.search),'search must be object');const sr=(value.search??{}) as Record<string,unknown>;fields(sr,['strategy','seed','maxDepth','batchSize','concurrency','uniformFraction','stagnationBatches','maxCandidates','maxQueueBytes','familyQuota'],'search');const s={strategy:'uniform',seed:42,maxDepth:3,batchSize:8,concurrency:4,uniformFraction:.2,stagnationBatches:20,maxCandidates:1000,maxQueueBytes:16*1024*1024,familyQuota:4,...sr};assert(['enumerator','uniform','novelty','boundary','feedback'].includes(String(s.strategy)),'strategy invalid');
  assert(value.oracle===undefined||record(value.oracle),'oracle must be object');const or=(value.oracle??{}) as Record<string,unknown>;fields(or,['profile','pairs','minimumSupport','maxControlViolationRate','minimumEffect','alpha','originalSlots','shrinkSlots'],'oracle');const profile=or.profile??'paired-v1';const o={profile,pairs:profile==='fixed-stat-v1'?64:8,minimumSupport:.75,maxControlViolationRate:.125,minimumEffect:0,alpha:.05,originalSlots:5,shrinkSlots:5,...or};assert(o.profile==='paired-v1'||o.profile==='fixed-stat-v1','oracle profile invalid');
  const b=value.budget;assert(record(b),'budget must be object');fields(b,['logicalRequests','httpAttempts','wallTimeSeconds','discoveryRequests','confirmationRequests','shrinkRequests','finalConfirmationRequests'],'budget');const budget={logicalRequests:integer(b.logicalRequests,'logicalRequests'),httpAttempts:integer(b.httpAttempts,'httpAttempts',0),wallTimeSeconds:integer(b.wallTimeSeconds,'wallTimeSeconds'),discoveryRequests:integer(b.discoveryRequests,'discoveryRequests',0),confirmationRequests:integer(b.confirmationRequests,'confirmationRequests',0),shrinkRequests:integer(b.shrinkRequests,'shrinkRequests',0),finalConfirmationRequests:integer(b.finalConfirmationRequests,'finalConfirmationRequests',0)};validateBudget(budget);const confirmationCost=3*integer(o.pairs,'pairs',1,1023);assert(budget.confirmationRequests>=confirmationCost,'budget cannot fund confirmation');
  assert(value.storage===undefined||record(value.storage),'storage must be object');const tr=(value.storage??{}) as Record<string,unknown>;fields(tr,['mode','directory','maxRunBytes','maxCorpusBytes','redactPaths'],'storage');const st={mode:'full',directory:'.jevfuzz',maxRunBytes:64*1024*1024,maxCorpusBytes:512*1024*1024,redactPaths:[],...tr};assert(['full','redacted','hash-only'].includes(String(st.mode))&&(st.mode!=='redacted'||Array.isArray(st.redactPaths)&&st.redactPaths.length>0),'storage invalid');
  const rr=value.reducers??{independentQuestions:false,optionalStatePaths:[],unorderedArrayPaths:[],prosePaths:[]};assert(record(rr),'reducers must be object');fields(rr,['independentQuestions','optionalStatePaths','unorderedArrayPaths','prosePaths'],'reducers');assert(typeof rr.independentQuestions==='boolean','independentQuestions invalid');const reducers={independentQuestions:rr.independentQuestions,optionalStatePaths:strings(rr.optionalStatePaths,'optionalStatePaths'),unorderedArrayPaths:strings(rr.unorderedArrayPaths,'unorderedArrayPaths'),prosePaths:strings(rr.prosePaths,'prosePaths')};for(const path of reducers.optionalStatePaths){assert(pathTokens(path)[0]==='state'&&pathTokens(path).length>1,'optional reducer path must be non-root state');for(const seed of seeds)atPath(seed.request,path);}for(const path of reducers.unorderedArrayPaths){for(const seed of seeds)assert(Array.isArray(atPath(seed.request,path)),'unordered reducer path must resolve to array');}for(const path of reducers.prosePaths){declaredContentPath(path);for(const seed of seeds)assert(typeof atPath(seed.request,path)==='string','prose reducer path must resolve to text');}
  assert(o.profile!=='fixed-stat-v1'||contracts.every(c=>c.relation!=='directional'),'fixed-stat-v1 excludes directional relations');
  assert(o.profile!=='fixed-stat-v1'||Number(o.originalSlots)+Number(o.shrinkSlots)>0,'fixed-stat-v1 requires reserved slots');
  const policy=parsePolicy(value.policy,seeds);assert(policy||contracts.every(c=>c.projection!=='policy'),'policy contracts require a policy');return {version:2,name:text(value.name,'campaign name'),seeds,provider:value.provider as CampaignConfig['provider'],contracts,search:{strategy:s.strategy as CampaignConfig['search']['strategy'],seed:integer(s.seed,'seed',0,0xffffffff),maxDepth:integer(s.maxDepth,'maxDepth',1,3),batchSize:integer(s.batchSize,'batchSize',1,256),concurrency:integer(s.concurrency,'concurrency',1,256),uniformFraction:unit(s.uniformFraction,'uniformFraction'),stagnationBatches:integer(s.stagnationBatches,'stagnationBatches',0,100_000),maxCandidates:integer(s.maxCandidates,'maxCandidates',1,100_000),maxQueueBytes:integer(s.maxQueueBytes,'maxQueueBytes',1,256*1024*1024),familyQuota:integer(s.familyQuota,'familyQuota',1,256)},oracle:{profile:o.profile as CampaignConfig['oracle']['profile'],pairs:integer(o.pairs,'pairs',1,1023),minimumSupport:unit(o.minimumSupport,'minimumSupport',true),maxControlViolationRate:unit(o.maxControlViolationRate,'maxControl'),minimumEffect:unit(o.minimumEffect,'minimumEffect'),alpha:unit(o.alpha,'alpha',true),originalSlots:integer(o.originalSlots,'originalSlots',0,10_000),shrinkSlots:integer(o.shrinkSlots,'shrinkSlots',0,10_000)},budget,storage:{mode:st.mode as CampaignConfig['storage']['mode'],directory:text(st.directory,'storage directory'),maxRunBytes:integer(st.maxRunBytes,'maxRunBytes',1,256*1024*1024),maxCorpusBytes:integer(st.maxCorpusBytes,'maxCorpusBytes',1,2*1024*1024*1024),redactPaths:strings(st.redactPaths,'redactPaths')},reducers,...(policy?{policy}:{}),duplicateSeeds};
}

export async function loadCampaign(filename:string):Promise<CampaignConfig>{const raw=await readJson(filename,1_000_000);assert(record(raw)&&Array.isArray(raw.seeds),'campaign seeds required');const root=dirname(resolve(filename)),expanded:unknown[]=[];for(const item of raw.seeds){if(typeof item!=='string'){expanded.push(item);continue;}const matches=globSync(item,{cwd:root}).filter(m=>!m.endsWith('/')).sort();assert(matches.length>0&&matches.length<=10_000,'seed glob invalid');for(const m of matches)expanded.push({id:basename(m),request:await readJson(resolve(root,m),1_000_000),source:relative(root,resolve(root,m))});}const out=parseCampaign({...raw,seeds:expanded},filename);out.storage.directory=resolve(root,out.storage.directory);return out;}
